server:
  port: 20009
spring:
  profiles:
    active: test
  application:
    name: shadingjdbc
  main:
    allow-bean-definition-overriding: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yoc.entity
  global-config:
    db-config:
      logic-delete-value: 1 #逻辑删除
      logic-not-delete-value: 0 #正常